### ISSUE TITLE
Issue with local install

### ISSUE THREAD

**Issue by jferragut** [breatheco-de/breathecode-cli#11]
Node version: 11.0.0

Upon running start:react-project, got the following output:

```
bc start:react-project
(node:38644) Warning: Mismatched version in bc-exercise-cli plugin manifest. Expected: 0.7.6 Received: 0.7.06
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
Error: The module '/usr/local/lib/node_modules/breathecode-cli/node_modules/sleep/build/Release/node_sleep.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.<anonymous> (/usr/local/lib/node_modules/breathecode-cli/node_modules/sleep/index.js:1:75)
```

**Comment by jferragut** [comment]
One issue related to this is node version level. You have to specifically have node version 8 or higher. At the time, my version was lower than that. 

Another issue that still remains is the Mismatch on the plugin manifest.

**Comment by alesanchezr** [comment]
Yes that freaking `manifest.json` has too be fixed.

**Comment by alesanchezr** [comment]
I think I know what the problem is. The current version of the cli is `0.7.07` but when the manifest is generated it ignores the `0` because it is probably being transformed into a number before the manifest generation. That is why the error is: `Mismatched version Expected: 0.7.7 Received: 0.7.07`.

The quick fix is to stop using version numbers with a `0` prepended.

That is a bug that is being inherited from [The Heroku CLI framework](https://github.com/oclif/oclif) which is the base technology around this CLI. I guess we can report it directly to them and also try to fix it. Maybe the will add us as contributors 😃

**Comment by alesanchezr** [comment]
Exactly a year later 😮
